PC_analysis <- function(int_data){
  # int_data is generated by generate_data()
  # It has one row per site opened at the point of interim analysis
  # y = number recruited; c = site ID; t = length of time site was open for
  # If no sites opened in time, a single row y=0, c=0, t=0 is returned
  
  # This function returns the statistics used by a standard progression criteria
  # approach to making a progression decision
  
  # First deal with the special case of no sites opened
  if(int_data$c[1] == 0){
    m_p <- 0
    n_p <- 0
    rate_p <- 0
    
    return(c(m_p, n_p, rate_p))
  } else {
    m_p <- nrow(int_data)
    n_p <- sum(int_data$y)
    rate_p <- n_p / sum(int_data$t)
    
    return(c(m_p, n_p, rate_p))
  }
  
  # int_data <- generate_data(m=20, int_t=0.5, target_n=300, beta_m=1.75, beta_s=0.3, v_df=10, v_sc=0.4, setup_r_a=10, setup_r_b=1)[[1]]
  # PC_analysis(int_data)
}
